---
- name: MacOS Development Playbook
  hosts: localhost
  roles:
    - role: development
      when: development_enabled | bool
    - role: docker
      tags: docker
      when: docker_enabled | bool
